apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-sandbox-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Akash-HC/gitops-argocd-demo.git
    targetRevision: master
    path: k8s/overlays/poc-sandbox/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-sandbox
  syncPolicy:
    automated: null

