apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-sandbox-frontend
  namespace: argocd
spec:
  project: poc-sandbox
  source:
    repoURL: https://github.com/Akash-HC/gitops-argocd-demo.git
    targetRevision: master
    path: k8s/overlay/poc-sandbox/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: poc-sandbox
  syncPolicy:
    automated: null
