apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-sandbox
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Akash-HC/gitops-argocd-demo.git
    targetRevision: main
    path: k8s/apps/poc-sandbox
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

